"""Data dictionary: what every table and column means, and the conventions behind them.

Single source of truth. It feeds
  - DuckDB comments (COMMENT ON ...), applied by `nyiso build`, so any query tool sees them
    (`SELECT table_name, column_name, comment FROM duckdb_columns()`),
  - docs/DATA.md and docs/data_dictionary.json, generated by `nyiso docs`,
  - tests/test_dictionary.py, which fails if any table or column is undocumented.

When you add a dataset, table or column, document it here. Statements marked "(verified)"
were checked against the data; see the verification notes in CONVENTIONS.
"""
from __future__ import annotations

from dataclasses import dataclass, field

# --------------------------------------------------------------------------- shared columns


@dataclass(frozen=True)
class Col:
    desc: str
    unit: str = ""


COLUMNS: dict[str, Col] = {
    # time
    "ts_utc": Col("Interval START in UTC. The join key for every time series. See conventions: timestamps.",
                  "UTC timestamp"),
    "ts_local": Col("Interval start in America/New_York wall-clock time (naive). Display only; ambiguous "
                    "on the fall-back day — never join on it.", "Eastern local time"),
    "day": Col("Calendar day in America/New_York (local day boundaries, so DST days have 23 or 25 hours).",
               "date"),
    "issue_date": Col("Date the forecast file was published (the MIS file date).", "date"),
    # identifiers
    "zone": Col("NYISO zone name as published by MIS: 11 internal load zones (WEST, GENESE, CENTRL, NORTH, "
                "MHK VL, CAPITL, HUD VL, MILLWD, DUNWOD, N.Y.C., LONGIL), 4 external proxy zones "
                "(H Q = Hydro-Québec, NPX = ISO-NE, O H = Ontario IESO, PJM), and 'NYISO'/'SYSTEM' totals "
                "where noted."),
    "ptid": Col("NYISO Point ID: numeric identifier of a pricing location (zone, generator node) or interface."),
    "node": Col("Generator pricing-node name as published (e.g. '59TH STREET_GT_1'). Join to `nodes` via ptid."),
    "fuel": Col("NYISO fuel category: Dual Fuel, Natural Gas, Nuclear, Hydro, Wind, Other Renewables "
                "(includes grid-scale solar and biomass), Other Fossil Fuels."),
    "facility": Col("Limiting transmission facility (constraint) name as published."),
    "facility_ptid": Col("PTID of the limiting facility."),
    "contingency": Col("Contingency under which the facility binds ('BASE CASE' = no contingency)."),
    "interface": Col("Interface name, e.g. 'CENTRAL EAST - VC', 'TOTAL EAST', or scheduled external lines "
                     "'SCH - PJ - NY'."),
    "market": Col("'DA' (day-ahead) or 'RT' (real-time)."),
    # prices
    "lbmp": Col("Locational Based Marginal Price. LBMP = energy + mlc − mcc (verified).", "$/MWh"),
    "mlc": Col("Marginal cost of losses component of LBMP (added).", "$/MWh"),
    "mcc": Col("Marginal cost of congestion component, NYISO sign: SUBTRACTED from LBMP, so a negative mcc "
               "means congestion raises the price at this location (verified).", "$/MWh"),
    "shadow_price": Col("Constraint shadow price as published in the 'Constraint Cost($)' column. Sign as "
                        "published, not normalized; both signs occur.", "$/MWh"),
    # quantities
    "load_mw": Col("Actual load (NYISO PAL), as published.", "MW"),
    "load_forecast_mw": Col("NYISO load forecast (ISOLF) for the hour.", "MW"),
    "gen_mw": Col("Generation by fuel category.", "MW"),
    "mw": Col("Behind-the-meter solar estimated actual output.", "MW"),
    "flow_mw": Col("Interface flow as published (MIS labels it MWH; it is a rate for the interval).", "MW"),
    "pos_limit_mw": Col("Positive-direction interface limit. ±9999 means no limit is enforced.", "MW"),
    "neg_limit_mw": Col("Negative-direction interface limit. ±9999 means no limit is enforced.", "MW"),
    # availability / external sources
    "available_utc": Col("Earliest time this value could have been known (UTC). As-of joins must filter "
                         "available_utc <= issue time. See conventions: as-of availability.", "UTC timestamp"),
    "station": Col("Weather station code (config.WEATHER_STATIONS: BUF, ROC, SYR, MSS, ART, ALB, POU, HPN, LGA, "
                   "JFK, ISP), each mapped to one or more NYISO zones."),
    "temp_c": Col("Air temperature at 2 m.", "°C"),
    "trade_date": Col("Gas trade date (spot for next-day flow).", "date"),
    "price_usd_mmbtu": Col("Henry Hub natural gas spot price.", "$/MMBtu"),
    "spin_10": Col("10-minute spinning reserve price.", "$/MWh"),
    "nonsync_10": Col("10-minute non-synchronous reserve price.", "$/MWh"),
    "or_30": Col("30-minute operating reserve price.", "$/MWh"),
    "reg_cap": Col("NYCA regulation capacity price.", "$/MWh"),
    "equipment": Col("Transmission equipment name as published (line, transformer, breaker)."),
    "first_seen_utc": Col("First snapshot in which this exact record appeared (start of a validity run).",
                          "UTC timestamp"),
    "last_seen_utc": Col("Last snapshot in which this exact record appeared (end of a validity run). The record "
                         "was part of the published schedule for all t in [first_seen_utc, last_seen_utc].",
                         "UTC timestamp"),
    "snapshots": Col("Number of snapshots in the validity run."),
    # aggregation bookkeeping
    "covered_s": Col("Seconds of the output bucket covered by data (300 = complete 5-min bucket, 3600 = complete "
                     "hour). Weight for further time-weighted averaging.", "seconds"),
}

# --------------------------------------------------------------------------- tables


@dataclass(frozen=True)
class Table:
    name: str
    layer: str               # "curated" (Parquet view), "derived" (DuckDB table), "reference", "report"
    description: str
    grain: str
    key: tuple[str, ...]
    source: str
    columns: tuple[str, ...]
    overrides: dict[str, str] = field(default_factory=dict)   # table-specific column descriptions
    notes: tuple[str, ...] = ()


_LBMP = ("ts_utc", "ts_local", "zone", "ptid", "lbmp", "mlc", "mcc")
_LBMP_NODE = ("ts_utc", "ts_local", "node", "ptid", "lbmp", "mlc", "mcc")
_CONSTRAINT = ("ts_utc", "ts_local", "facility", "facility_ptid", "contingency", "shadow_price")
_RT_NOTE = ("Published per RTD interval, stamped at interval END (shifted to start). ~4% of intervals are "
            "not 5 minutes; do not average rows naively — use the time-weighted tables or store/timeweight.py.")

TABLES: dict[str, Table] = {t.name: t for t in [
    # ---------------- curated (one DuckDB view per dataset over data/curated/<name>/**.parquet)
    Table("da_lbmp_zone", "curated", "Day-ahead LBMP by zone.", "hourly", ("ts_utc", "ptid"),
          "MIS damlbmp/*damlbmp_zone.csv", _LBMP),
    Table("da_lbmp_node", "curated", "Day-ahead LBMP by generator node (~750 nodes).", "hourly", ("ts_utc", "ptid"),
          "MIS damlbmp/*damlbmp_gen.csv", _LBMP_NODE),
    Table("rt_lbmp_zone", "curated", "Real-time LBMP by zone, per RTD interval.", "5-min (irregular)",
          ("ts_utc", "ptid"), "MIS realtime/*realtime_zone.csv", _LBMP, notes=(_RT_NOTE,)),
    Table("rt_lbmp_node", "curated", "Real-time LBMP by generator node, per RTD interval. Largest dataset "
          "(~365M rows).", "5-min (irregular)", ("ts_utc", "ptid"), "MIS realtime/*realtime_gen.csv", _LBMP_NODE,
          notes=(_RT_NOTE, "NYISO archive is missing 2026-08-01..26; the map falls back to rt_lbmp_node_hourly.")),
    Table("rt_lbmp_zone_hourly", "curated", "NYISO integrated (time-weighted hourly) real-time LBMP by zone.",
          "hourly", ("ts_utc", "ptid"), "MIS rtlbmp/*rtlbmp_zone.csv", _LBMP,
          notes=("NYISO archive is missing 2026-07-01..20; lbmp_zone_hourly fills those hours from 5-min data.",)),
    Table("rt_lbmp_node_hourly", "curated", "NYISO integrated (hourly) real-time LBMP by generator node.",
          "hourly", ("ts_utc", "ptid"), "MIS rtlbmp/*rtlbmp_gen.csv", _LBMP_NODE),
    Table("load", "curated", "Actual load by zone (PAL).", "5-min (irregular)", ("ts_utc", "ptid"),
          "MIS pal/*pal.csv", ("ts_utc", "ts_local", "zone", "ptid", "load_mw"),
          notes=("Stamped at interval START. 11 internal zones; no system total row (see load_5m).",)),
    Table("load_forecast", "curated", "NYISO load forecast by zone, every published issue.", "hourly per issue",
          ("ts_utc", "zone", "issue_date"), "MIS isolf/*isolf.csv (wide file melted to long)",
          ("ts_utc", "ts_local", "zone", "load_forecast_mw", "issue_date"),
          overrides={"zone": "Zone name upper-cased from the ISOLF header, plus 'NYISO' = system total."},
          notes=("Each issue covers the issue day plus 5 days ahead (horizon 0–5 days, verified). "
                 "For a day-ahead forecast use load_forecast_da.",)),
    Table("fuel_mix", "curated", "Real-time generation by fuel category.", "5-min (irregular)", ("ts_utc", "fuel"),
          "MIS rtfuelmix/*rtfuelmix.csv", ("ts_utc", "ts_local", "fuel", "gen_mw"), notes=(_RT_NOTE,)),
    Table("btm_solar", "curated", "Behind-the-meter solar, estimated actual, by zone.", "hourly", ("ts_utc", "zone"),
          "MIS btmactualforecast/*BTMEstimatedActual.csv", ("ts_utc", "ts_local", "zone", "mw"),
          overrides={"zone": "Internal zone name, or 'SYSTEM' = NYCA total (equals the sum of zones, verified)."},
          notes=("Reported separately from load_mw; net load in this project does not subtract it. "
                 "NYISO is missing ~20 whole days.",)),
    Table("da_constraints", "curated", "Day-ahead binding transmission constraints.", "hourly, binding only",
          ("ts_utc", "facility", "contingency"), "MIS DAMLimitingConstraints/*DAMLimitingConstraints.csv",
          _CONSTRAINT, notes=("Only binding (facility, contingency) pairs are listed; absence = not binding.",)),
    Table("rt_constraints", "curated", "Real-time binding transmission constraints.", "5-min, binding only",
          ("ts_utc", "facility", "contingency"), "MIS LimitingConstraints/*LimitingConstraints.csv", _CONSTRAINT,
          notes=("Only binding intervals are listed. Stamped at interval START.",)),
    Table("interface_flows", "curated", "Interface flows and limits (internal interfaces and external lines).",
          "5-min (irregular)", ("ts_utc", "interface"), "MIS ExternalLimitsFlows/*ExternalLimitsFlows.csv",
          ("ts_utc", "ts_local", "interface", "ptid", "flow_mw", "pos_limit_mw", "neg_limit_mw"),
          overrides={"ptid": "Interface Point ID."},
          notes=("Stamped at interval START. Positive direction is NYISO's defined direction for each "
                 "interface (not re-derived here).",)),

    Table("da_asp", "curated", "Day-ahead ancillary service prices by zone.", "hourly", ("ts_utc", "ptid"),
          "MIS damasp/*damasp.csv", ("ts_utc", "ts_local", "zone", "ptid", "spin_10", "nonsync_10", "or_30", "reg_cap"),
          notes=("Reserve prices spike under scarcity; a leading indicator of RT price spikes.",)),
    Table("rt_asp", "curated", "Real-time ancillary service prices by zone, per RTD interval.", "5-min (irregular)",
          ("ts_utc", "ptid"), "MIS rtasp/*rtasp.csv",
          ("ts_utc", "ts_local", "zone", "ptid", "spin_10", "nonsync_10", "or_30", "reg_cap", "reg_move"),
          overrides={"reg_move": "NYCA regulation movement price ($/MW)."}, notes=(_RT_NOTE,)),
    Table("sched_outages", "curated", "Scheduled transmission outages as published over time (point-in-time).",
          "validity runs", ("ptid", "equipment", "sched_out_utc", "sched_in_utc", "first_seen_utc"),
          "MIS schedlineoutages/*SCLineOutages.csv (schedule re-published every 5 min; compacted)",
          ("ptid", "equipment", "sched_out_utc", "sched_in_utc", "first_seen_utc", "last_seen_utc", "snapshots"),
          overrides={"ptid": "Equipment Point ID.",
                     "sched_out_utc": "Scheduled outage start (published local time -> UTC).",
                     "sched_in_utc": "Scheduled return to service. For outages in progress NYISO rolls this forward "
                                     "hourly, so one outage appears as several records."},
          notes=("To get the schedule known at time t: first_seen_utc <= t <= last_seen_utc. Runs are split at "
                 "month boundaries and at publishing gaps > 15 min.",
                 "Ambiguous fall-back local times in sched_out/in are read as EDT (no marker published).")),
    Table("rt_line_outages", "curated", "Transmission equipment out of service in real time (point-in-time).",
          "validity runs", ("ptid", "equipment", "outage_start_utc", "first_seen_utc"),
          "MIS realtimelineoutages/*RTLineOutages.csv (compacted snapshots)",
          ("ptid", "equipment", "outage_start_utc", "first_seen_utc", "last_seen_utc", "snapshots"),
          overrides={"ptid": "Equipment Point ID.", "outage_start_utc": "When the equipment went out (UTC)."}),
    Table("gas_henry_hub", "curated", "Henry Hub natural gas spot price (EIA).", "daily (trade days)",
          ("trade_date",), "EIA RNGWHHD (hist_xls/RNGWHHDd.xls); public domain",
          ("trade_date", "price_usd_mmbtu", "available_utc"),
          notes=("available_utc = 00:00 ET on the day after the trade date (backtest rule). EIA itself posts "
                 "weekly; live use needs a same-day source.",
                 "EIA's NYMEX futures series (RNGC1-4) stopped on 2024-04-05, so there is no free gas forward "
                 "curve; long-horizon energy norms need another source.")),
    Table("weather_obs", "curated", "Hourly weather observations at NY stations (NOAA GHCNh).", "hourly",
          ("ts_utc", "station"), "NOAA NCEI GHCNh by-year PSV; public domain",
          ("ts_utc", "station", "temp_c", "dewpoint_c", "wind_ms", "n_reports", "available_utc"),
          overrides={"ts_utc": "Observation hour (UTC); reports within ±30 min of the hour are averaged.",
                     "dewpoint_c": "Dew point temperature (°C).", "wind_ms": "Wind speed (m/s).",
                     "n_reports": "Number of station reports averaged into the hour."},
          notes=("Physically implausible values are dropped; GHCNh quality codes are not otherwise filtered.",)),
    Table("weather_fcst", "curated", "GFS 2 m temperature forecasts by lead time (forecast vintages).",
          "hourly x lead", ("ts_utc", "station", "lead_days"),
          "Open-Meteo previous-runs API, model pinned to gfs_seamless. RESEARCH USE ONLY (non-commercial licence)",
          ("ts_utc", "station", "lead_days", "temp_c", "available_utc"),
          overrides={"ts_utc": "Valid (forecast target) hour, UTC.",
                     "lead_days": "Forecast made lead_days x 24 h before the valid hour (0 = latest run, ~analysis).",
                     "temp_c": "Forecast 2 m temperature (°C).",
                     "available_utc": "valid − lead_days × 24 h + 6 h model latency (conservative); lead 0: valid + 6 h."},
          notes=("Only GFS temperature is archived back to 2021; other variables start 2024, so v1 uses temperature "
                 "only to keep the feature consistent across the training history.",
                 "Upstream gap: no lead 1-7 forecasts for valid times 2023-12-30 .. 2024-01-19 (lead 0 only). As-of "
                 "features are NULL there by design; models must handle missing temperature.")),

    # ---------------- derived (DuckDB tables built by `nyiso build`)
    Table("rt_lbmp_zone_5m", "derived", "Real-time zonal LBMP time-weighted onto the 5-minute grid.",
          "5-min", ("ts_utc", "zone"), "rt_lbmp_zone via store/timeweight.py",
          ("ts_utc", "zone", "lbmp", "mlc", "mcc", "covered_s")),
    Table("fuel_mix_5m", "derived", "Fuel mix time-weighted onto the 5-minute grid.", "5-min", ("ts_utc", "fuel"),
          "fuel_mix via store/timeweight.py", ("ts_utc", "fuel", "gen_mw", "covered_s")),
    Table("load_zone_5m", "derived", "Zonal load time-weighted onto the 5-minute grid.", "5-min", ("ts_utc", "zone"),
          "load via store/timeweight.py (start-stamped)", ("ts_utc", "zone", "load_mw", "covered_s")),
    Table("load_5m", "derived", "load_zone_5m plus a system total row.", "5-min", ("ts_utc", "zone"),
          "load_zone_5m", ("ts_utc", "zone", "load_mw", "covered_s"),
          overrides={"zone": "Internal zone, or 'NYISO' = sum of the 11 zones.",
                     "covered_s": "Seconds covered; for 'NYISO' the minimum across zones."}),
    Table("system_5m", "derived", "System-level series for the Conditions tab.", "5-min", ("ts_utc",),
          "load_5m, fuel_mix_5m, rt_lbmp_zone_5m",
          ("ts_utc", "ts_local", "load_mw", "covered_s", "net_load_mw", "rt_lbmp"),
          overrides={"load_mw": "NYISO total load.",
                     "net_load_mw": "Load minus wind (GridStatus convention). NULL until fuel mix is posted.",
                     "rt_lbmp": "Simple average of the 11 internal zones' time-weighted RT LBMP ($/MWh). "
                                "Not load-weighted; not a NYISO-published figure."}),
    Table("lbmp_zone_hourly", "derived", "Hourly DA and RT LBMP by zone side by side, with DA−RT spread.",
          "hourly", ("ts_utc", "zone"), "da_lbmp_zone, rt_lbmp_zone_hourly, rt_lbmp_zone_5m",
          ("ts_utc", "ts_local", "zone", "da_lbmp", "da_mlc", "da_mcc", "rt_lbmp", "rt_mlc", "rt_mcc",
           "rt_source", "rt_flag", "da_rt_spread"),
          overrides={"da_lbmp": "Day-ahead LBMP ($/MWh).", "da_mlc": "Day-ahead loss component ($/MWh).",
                     "da_mcc": "Day-ahead congestion component, NYISO sign ($/MWh).",
                     "rt_lbmp": "Real-time hourly LBMP ($/MWh); see rt_source.",
                     "rt_mlc": "Real-time loss component ($/MWh).",
                     "rt_mcc": "Real-time congestion component, NYISO sign ($/MWh).",
                     "rt_source": "'integrated' = NYISO's published hourly value; 'derived_twa' = time-weighted "
                                  "from 5-min intervals because NYISO's hourly file is missing (2026-07-01..20).",
                     "rt_flag": "NULL = OK. 'integrated_vs_5m_mismatch' = NYISO's integrated value differs from "
                                "its own 5-min data by ≥ $0.02 (NYISO-side missing intervals or an hour in "
                                "progress at download). Accepted; value kept as published.",
                     "da_rt_spread": "da_lbmp − rt_lbmp ($/MWh). Positive = DA priced above RT."},
          notes=("Rows exist for tomorrow's DA hours with NULL RT.",)),
    Table("fuel_mix_hourly", "derived", "Hourly time-weighted generation by fuel.", "hourly", ("ts_utc", "fuel"),
          "fuel_mix_5m", ("ts_utc", "fuel", "gen_mw")),
    Table("load_hourly", "derived", "Hourly time-weighted load by zone (incl. 'NYISO' total).", "hourly",
          ("ts_utc", "zone"), "load_5m", ("ts_utc", "zone", "load_mw")),
    Table("load_forecast_da", "derived", "Day-ahead load forecast: the value issued the calendar day before the "
          "target local day.", "hourly", ("ts_utc", "zone"), "load_forecast",
          ("ts_utc", "zone", "load_forecast_mw")),
    Table("interface_flows_hourly", "derived", "Hourly time-weighted interface flows and limits.", "hourly",
          ("ts_utc", "interface"), "interface_flows via store/timeweight.py (start-stamped)",
          ("ts_utc", "interface", "flow_mw", "pos_limit_mw", "neg_limit_mw", "covered_s")),
    Table("constraints_daily", "derived", "Binding constraints summarized per local day.", "daily",
          ("market", "day", "facility", "contingency"), "da_constraints, rt_constraints",
          ("market", "day", "facility", "contingency", "intervals", "hours_binding", "sum_cost", "max_abs_cost",
           "avg_cost"),
          overrides={"intervals": "Number of binding intervals (hours for DA, RTD intervals for RT).",
                     "hours_binding": "DA: intervals. RT: intervals × 5/60 — assumes nominal 5-min intervals "
                                      "(approximation; RT constraint rows are not time-weighted).",
                     "sum_cost": "Sum of shadow_price over binding intervals ($/MWh summed; sign as published).",
                     "max_abs_cost": "Largest |shadow_price| ($/MWh).",
                     "avg_cost": "Mean shadow_price over binding intervals ($/MWh)."}),
    Table("daily_summary", "derived", "One row per local day: KPIs used by the dashboard and Trends.", "daily",
          ("day",), "system_5m, lbmp_zone_hourly, fuel_mix_5m",
          ("day", "avg_load_mw", "peak_load_mw", "avg_net_load_mw", "avg_da_lbmp", "avg_rt_lbmp", "main_source",
           "avg_gen_mw", "renewable_share", "carbon_free_share"),
          overrides={"avg_load_mw": "Time-weighted average NYISO load (MW).",
                     "peak_load_mw": "Maximum 5-min NYISO load (MW).",
                     "avg_net_load_mw": "Time-weighted average load minus wind (MW).",
                     "avg_da_lbmp": "Mean hourly DA LBMP over hours × 11 internal zones ($/MWh).",
                     "avg_rt_lbmp": "Mean hourly RT LBMP over hours × 11 internal zones ($/MWh); same basis as DA.",
                     "main_source": "Fuel with the highest average generation that day.",
                     "avg_gen_mw": "Time-weighted average total generation across fuel categories (MW).",
                     "renewable_share": "(Wind + Hydro + Other Renewables) / total generation (fraction 0–1). "
                                        "Excludes BTM solar.",
                     "carbon_free_share": "renewable_share plus Nuclear (fraction 0–1)."}),
    Table("fuel_mix_daily", "derived", "Daily average generation by fuel, including BTM solar.", "daily",
          ("day", "fuel"), "fuel_mix_5m, btm_solar", ("day", "fuel", "avg_mw"),
          overrides={"fuel": "NYISO fuel category, plus 'BTM Solar' (from btm_solar SYSTEM).",
                     "avg_mw": "Time-weighted daily average (MW)."}),
    Table("lbmp_zone_daily", "derived", "Daily average DA/RT LBMP and spread by zone.", "daily", ("day", "zone"),
          "lbmp_zone_hourly", ("day", "zone", "avg_da_lbmp", "avg_rt_lbmp", "avg_spread"),
          overrides={"avg_da_lbmp": "Mean of hourly DA LBMP ($/MWh).", "avg_rt_lbmp": "Mean of hourly RT LBMP ($/MWh).",
                     "avg_spread": "Mean of hourly DA − RT ($/MWh)."}),

    # ---------------- reference
    Table("nodes", "reference", "Generator nodes with coordinates (data/ref/nodes.parquet).", "one row per generator",
          ("ptid",), "MIS generator/generator.csv (current list; retired units are absent)",
          ("ptid", "name", "zone", "subzone", "lat", "lon", "active", "aggregation_ptid", "has_prices"),
          overrides={"name": "Generator name (matches `node` in LBMP tables).",
                     "subzone": "Transmission-owner subzone, e.g. 'CON ED NY CITY'.",
                     "lat": "Latitude (WGS84) as published; NULL for ~270 generators.",
                     "lon": "Longitude (WGS84) as published.",
                     "active": "Generator flagged active by NYISO.",
                     "aggregation_ptid": "PTID of the aggregation the unit prices under, if any.",
                     "has_prices": "True if the PTID appears in da_lbmp_node history."}),
]}

# Files that are not DuckDB objects
FILES: dict[str, str] = {
    "data/raw/<dataset>/<YYYYMM>.zip": "Immutable cache of NYISO MIS monthly archives (one CSV per day). "
                                        "Never edited; delete a file to force re-download.",
    "data/raw/<dataset>/daily/<YYYYMMDD>.csv": "Daily-file fallback for days missing from a monthly archive.",
    "data/curated/<dataset>/year=YYYY/month=MM/part.parquet": "Parsed, typed, deduplicated data (zstd). One file "
        "per source month; the curated views read these. Rebuild with `nyiso backfill --rebuild`.",
    "data/nyiso.duckdb": "Views over curated Parquet + derived tables. Disposable; `nyiso build` recreates it.",
    "data/ref/nodes.parquet": "Generator nodes (see table `nodes`).",
    "data/ref/loads.parquet": "Load points: name, ptid, subzone, zone (no coordinates are published).",
    "data/ref/zones.geojson": "APPROXIMATE zone polygons (county-based; see conventions: zone boundaries).",
    "data/ref/reference_report.json": "Counts of mapped/unmapped nodes from `nyiso reference`.",
    "data/coverage.parquet": "Per dataset per local day: intervals present vs expected, coverage fraction "
                             "(`nyiso validate`).",
}

# --------------------------------------------------------------------------- conventions

CONVENTIONS: list[tuple[str, str]] = [
    ("Timestamps",
     "Every series is keyed on `ts_utc` = interval START in UTC. `ts_local` is the same instant in "
     "America/New_York for display. Daily rollups use local calendar days (23/25 hours on DST days)."),
    ("Interval-ending stamps",
     "NYISO stamps real-time LBMP (realtime_*) and fuel mix at interval END; the parser shifts them to start "
     "(stamp − 5 min in the curated tables). Load, interface flows, constraints, DA and integrated hourly "
     "files are stamped at interval START."),
    ("Fall-back DST day",
     "Files with a Time Zone column (EDT/EST) are localized from it. Otherwise, per entity in file order, every "
     "row after local time steps backward (or repeats) is EST. 'First occurrence = EDT' is wrong: off-grid "
     "stamps in the EST hour (e.g. 01:02:48 on 2021-11-07) occur once. Regression test: "
     "tests/test_parse.py::test_offgrid_stamps_in_repeated_hour_are_est."),
    ("Irregular RTD intervals and time weighting",
     "~4% of real-time intervals are not 5 minutes (delayed RTD runs publish stamps like 02:59:55). Curated "
     "tables keep stamps as published. Derived tables rebuild each interval's true [start, end) from the "
     "neighbouring stamp (gaps > 15 min are treated as missing data with a nominal 5-min interval) and "
     "time-weight onto 5-min/hourly buckets (store/timeweight.py). Verified: reproduces NYISO's integrated "
     "hourly RT LBMP to the cent in every hour 2021–2024. Averages over derived tables should weight by covered_s."),
    ("Price components",
     "LBMP = energy + mlc − mcc (verified: energy is identical across all zones in an interval). "
     "A negative mcc means congestion raises the local price."),
    ("Accepted data flags",
     "lbmp_zone_hourly.rt_flag marks hours where NYISO's integrated RT differs from its own 5-min data "
     "(2025-05-27 19:00–21:00: NYISO 5-min intervals missing; the latest hour at download time). Values are "
     "kept as published."),
    ("Known NYISO archive gaps",
     "rt_lbmp_node: 2026-08-01..26 missing (map falls back to hourly). rt_lbmp_zone_hourly: 2026-07-01..20 "
     "missing (filled, rt_source='derived_twa'). btm_solar: ~20 whole days missing. Full per-day detail: "
     "data/coverage.parquet."),
    ("Dashboard KPI definitions",
     "Price = simple average of the 11 internal zones' RT LBMP (not load-weighted; GridStatus uses a slightly "
     "different figure). Net load = load − wind. Main source = largest fuel at the selected interval."),
    ("Zone boundaries",
     "No openly licensed NYISO zone boundary file exists (NYPA's ArcGIS layer forbids redistribution). "
     "zones.geojson assigns Census counties to zones by majority vote of generator nodes, with overrides "
     "(Putnam→HUD VL, Livingston→GENESE, Westchester split at 41.13°N into MILLWD/DUNWOD). Approximate; "
     "drop an official file at data/ref/zones_override.geojson to replace it."),
    ("Node mapping",
     "Only generator nodes have coordinates. 561 of 758 priced nodes are mapped; the rest lack coordinates or "
     "are retired units absent from the current generator.csv."),
    ("As-of availability",
     "Forecast issue time for D+1 = 05:00 ET on D−1 (NYISO DAM bid deadline, MST 4.2; results post by 11:00). "
     "ISOLF file dated F is posted ~07:05–08:20 ET on F (MIS P-7 index), so it is usable from 08:30 ET on F: a "
     "05:00 D−1 issue may only use the ISOLF file of D−2. DA prices for D−1 are known from 11:00 on D−2. RT data "
     "is known up to its interval end. Henry Hub for trade date T: 00:00 ET on T+1. Weather obs: hour + 30 min. "
     "Weather forecasts: see weather_fcst.available_utc. Outage schedules: first_seen_utc. External tables carry "
     "available_utc explicitly."),
    ("Licensing",
     "NYISO MIS, NOAA and EIA data are public. weather_fcst comes from Open-Meteo's free, non-commercial API and "
     "is for research/backtesting only; replace it with a licensed forecast source before any live trading use."),
    ("Units",
     "Prices $/MWh; power MW (MIS labels some flow/limit columns 'MWH' — they are interval rates in MW); "
     "shares are fractions 0–1."),
]
