"""DART I/O edge: loads stored and live forecasts, writes `live_dart`, paper P&L and the report files.

The rules and P&L are pure and live in `dart_rules.py`; this module only fetches DataFrames for them and stores results.
Declarations and results: docs/ROADMAP.md (DART prototype, M4), docs/experiments/dart_prototype.md, dart_v2.md.
"""
from __future__ import annotations

import json
from datetime import UTC

import duckdb
import pandas as pd

from lmpsignal import dart_rules as dr
from lmpsignal.config import EXPERIMENTS_DIR, FEATURES_DB, HOLDOUT_START
from lmpsignal.evaluate import QCOLS


def load_long(run_spec: str) -> pd.DataFrame:
    """Hourly total-price rows (all zones, QCOLS, mean, y) from one or more '+'-joined runs; later runs win on duplicates."""
    frames = [duckdb.sql(f"""
        SELECT delivery_date, ts_utc, zone, hour_local, market, mean, {', '.join(QCOLS)}, y
        FROM read_parquet('{(EXPERIMENTS_DIR / rid).as_posix()}/fold=*.parquet')
        WHERE component = 'total'""").df() for rid in run_spec.split("+")]
    return pd.concat(frames, ignore_index=True).drop_duplicates(["ts_utc", "zone", "market"], keep="last")


def load_lags() -> pd.DataFrame:
    con = duckdb.connect(str(FEATURES_DB), read_only=True)
    try:
        return con.execute("SELECT ts_utc, zone, lag_da_d1_total, lag_rt_d2_total FROM panel").df()
    finally:
        con.close()


def load_spike(run_id: str) -> pd.DataFrame:
    return duckdb.sql(f"""SELECT ts_utc, zone, p_spike, mean AS spike_mean
                          FROM read_parquet('{(EXPERIMENTS_DIR / run_id).as_posix()}/fold=*.parquet')""").df()


def load_signal(run_spec: str) -> pd.DataFrame:
    """Hourly zone rows with DA/RT total forecast mean, q05, q95 and outcomes, from one or more '+'-joined runs."""
    return dr.pivot_signal(load_long(run_spec))


def positions_v2(signal_run: str, spike_run: str, lags: pd.DataFrame | None = None) -> pd.DataFrame:
    """DART v2 backtest rows over a stored signal run and spike run. See docs/ROADMAP.md, M4 declaration."""
    return dr.positions_v2(load_long(signal_run), load_spike(spike_run), load_lags() if lags is None else lags)


def backtest_v2(signal_run: str, spike_run: str) -> pd.DataFrame:
    return dr.backtest_v2_table(positions_v2(signal_run, spike_run))


def backtest(validation_run: str, holdout_spec: str | None) -> tuple[pd.DataFrame, pd.DataFrame]:
    w = load_signal(validation_run + (("+" + holdout_spec) if holdout_spec else ""))
    w["delivery_date"] = pd.to_datetime(w["delivery_date"])
    w["period"] = ["holdout" if d >= pd.Timestamp(HOLDOUT_START) else "validation" for d in w["delivery_date"]]
    return dr.backtest_tables(dr.positions(w, load_lags()))


def write_report(summary: pd.DataFrame, by_zone: pd.DataFrame, path) -> None:
    doc =["# DART prototype backtest", "", "_Generated by `lmp dart`. Rule and caveats: `pipeline/lmpsignal/dart_rules.py`._", "",
           f"Positions per internal zone and hour, at most 1 MW, cost ${dr.COST:.2f}/MWh traded. P&L in $ per 1 MW position "
           "limit summed over zones and hours. Validation = stored out-of-sample forecasts 2022-10..2025-09; holdout = "
           "the M7 run 2025-10..2026-09.", "", "## Summary", "", dr.md(summary), "", "## P&L by zone", "",
           dr.md(by_zone.pivot(index="zone", columns="period", values="pnl_signal").reset_index()), "",
           "## Diagnosis (2026-10-05)", "",
           "The declared rule loses despite a 55-56% hit rate: losing hours are much larger than winning ones. Signal "
           "v1's point forecast behaves like a median (LightGBM-L1 targets the median; LEAR is fit in asinh space), "
           "and RT prices are right-skewed, so the RT forecast understates the RT mean more than DA: validation "
           "averages RT 38.0 forecast vs 42.5 actual, DA 41.2 vs 42.6. The forecast spread therefore leans ~+$3 to "
           "INC while the realized spread averages ~0, and RT spikes punish the INC bias. A DART rule needs "
           "conditional-mean forecasts (mean-targeting models, or the forecast distribution's mean) and explicit RT "
           "spike risk (M3b, joint DA/RT in M4). Logged in docs/RESEARCH_LOG.md; the declared rule is not re-tuned.", ""]
    path.write_text("\n".join(doc), encoding="utf-8")


def lineage_holdout(signal: str) -> str | None:
    p = EXPERIMENTS_DIR / "m7_lineage.json"
    if not p.exists():
        return None
    lin = json.loads(p.read_text())
    return lin.get(signal) if lin.get("candidate") == signal else None


# ----------------------------------------------------------------------------- DART v2 live paper trading
# Positions for delivery day D from the live signal (`live_forecasts`) and the live spike member (`live_spike`), with
# rho from the signal's residuals over the 365 days before D's training end (validation run + M7 holdout + earlier
# live days). Paper only: validated on the validation folds, no out-of-sample confirmation yet (ROADMAP, M4 result).

LIVE_SCHEMA = """CREATE TABLE IF NOT EXISTS live_dart (
    rule VARCHAR, signal VARCHAR, issue_utc TIMESTAMPTZ, delivery_date DATE, ts_utc TIMESTAMPTZ, zone VARCHAR,
    hour_local INTEGER, spread_fcst DOUBLE, spread_scale DOUBLE, rho DOUBLE, p_spike DOUBLE, x_mw DOUBLE,
    git_commit VARCHAR, created_utc TIMESTAMPTZ)"""


def outcomes() -> pd.DataFrame:
    """Realized DA and RT total prices by ts_utc and zone (empty y until the hour settles)."""
    con = duckdb.connect(str(FEATURES_DB), read_only=True)
    try:
        return con.execute("SELECT ts_utc, zone, da_total AS y_da, rt_total AS y_rt FROM panel").df()
    finally:
        con.close()


def residual_history(signal: str) -> pd.DataFrame:
    """delivery_date, zone, r_da, r_rt of the signal's total-price mean: validation + M7 holdout + live days."""
    from lmpsignal import registry
    from lmpsignal.diagnostics import completed_runs

    runs = [completed_runs([signal])[signal]]
    hold = lineage_holdout(signal)
    runs += hold.split("+") if hold else []
    d = pd.concat([duckdb.sql(f"""SELECT delivery_date, ts_utc, zone, market, mean, y
                                  FROM read_parquet('{(EXPERIMENTS_DIR / r).as_posix()}/fold=*.parquet')
                                  WHERE component = 'total'""").df() for r in runs], ignore_index=True)
    d = d.drop_duplicates(["ts_utc", "zone", "market"], keep="last")
    w = d.pivot_table(index=["delivery_date", "ts_utc", "zone"], columns="market", values=["mean", "y"]).reset_index()
    w.columns = ["_".join(c).strip("_") for c in w.columns]
    with registry.connect(read_only=True) as con:
        has = con.execute("SELECT count(*) FROM duckdb_tables() WHERE table_name = 'live_forecasts'").fetchone()[0]
        lv = con.execute("""SELECT delivery_date, ts_utc, zone, market, mean FROM live_forecasts
                            WHERE signal = ? AND component = 'total'""", [signal]).df() if has else pd.DataFrame()
    if not lv.empty:
        lw = lv.pivot_table(index=["delivery_date", "ts_utc", "zone"], columns="market", values="mean").reset_index()
        lw = lw.rename(columns={"da": "mean_da", "rt": "mean_rt"}).merge(outcomes(), on=["ts_utc", "zone"], how="left")
        w = pd.concat([w, lw[lw["ts_utc"] > w["ts_utc"].max()]], ignore_index=True)
    w["delivery_date"] = pd.to_datetime(w["delivery_date"])
    w = w.dropna(subset=["mean_da", "mean_rt", "y_da", "y_rt"])
    return w.assign(r_da=w["y_da"] - w["mean_da"], r_rt=w["y_rt"] - w["mean_rt"])


def live_inputs(d, signal: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Live forecast rows (total price, QCOLS) and spike-member rows for delivery day D."""
    from lmpsignal import registry

    with registry.connect(read_only=True) as con:
        f = con.execute(f"""SELECT issue_utc, delivery_date, ts_utc, zone, hour_local, market, {', '.join(QCOLS)}
                            FROM live_forecasts WHERE signal = ? AND delivery_date = ? AND component = 'total'""",
                        [signal, d]).df()
        has = con.execute("SELECT count(*) FROM duckdb_tables() WHERE table_name = 'live_spike'").fetchone()[0]
        sp = con.execute("""SELECT ts_utc, zone, p_spike, mean AS spike_mean FROM live_spike
                            WHERE delivery_date = ? AND model = 'spike_full'""", [d]).df() if has else pd.DataFrame()
    if f.empty or sp.empty:
        raise ValueError(f"need live_forecasts and live_spike for {d}: run `lmp forecast` and `lmp risk` first")
    return f, sp


def live_v2(d, signal: str | None = None) -> pd.DataFrame:
    """DART v2 paper positions for delivery day D -> experiments.duckdb live_dart."""
    from datetime import datetime

    from lmpsignal import registry
    from lmpsignal.cv import month_fold
    from lmpsignal.presets import SIGNAL_V1

    signal = signal or SIGNAL_V1
    f, sp = live_inputs(d, signal)
    pos = dr.live_positions_v2(f, sp, residual_history(signal), pd.Timestamp(month_fold(d).train_end))
    out = pos.assign(rule="v2", signal=signal, git_commit=registry.git_commit(), created_utc=datetime.now(UTC))
    with registry.connect() as con:
        con.execute(LIVE_SCHEMA)
        con.execute("DELETE FROM live_dart WHERE rule = 'v2' AND delivery_date = ?", [d])
        con.register("o", out)
        con.execute("""INSERT INTO live_dart SELECT rule, signal, issue_utc, delivery_date, ts_utc, zone, hour_local,
                       spread_fcst, spread_scale, rho, p_spike, x_mw, git_commit, created_utc FROM o""")
    return out


def paper() -> pd.DataFrame:
    """Daily paper P&L of the live DART v2 positions on settled days (DA and RT outcomes known)."""
    from lmpsignal import registry

    with registry.connect(read_only=True) as con:
        if not con.execute("SELECT count(*) FROM duckdb_tables() WHERE table_name = 'live_dart'").fetchone()[0]:
            return pd.DataFrame()
        x = con.execute("SELECT delivery_date, ts_utc, zone, x_mw FROM live_dart WHERE rule = 'v2'").df()
    return dr.paper_pnl(x, outcomes())
