"""Publish the data dictionary: DuckDB comments + docs/DATA.md + docs/data_dictionary.json."""
from __future__ import annotations

import json
from datetime import datetime

import duckdb

from nyiso.config import DATA, ROOT
from nyiso.dictionary import COLUMNS, CONVENTIONS, FILES, TABLES, Table

DOCS = ROOT / "docs"


def col_desc(t: Table, c: str) -> str:
    if c in t.overrides:
        return t.overrides[c]
    col = COLUMNS.get(c)
    if col is None:
        return ""
    return f"{col.desc} [{col.unit}]" if col.unit else col.desc


def _q(s: str) -> str:
    return s.replace("'", "''")


def _objects(con: duckdb.DuckDBPyConnection) -> dict[str, str]:
    """name -> 'VIEW' | 'TABLE' for project objects in the database."""
    rows = con.execute("SELECT view_name, 'VIEW' FROM duckdb_views() WHERE NOT internal "
                       "UNION ALL SELECT table_name, 'TABLE' FROM duckdb_tables() WHERE NOT internal").fetchall()
    return dict(rows)


def apply_comments(con: duckdb.DuckDBPyConnection) -> None:
    objs = _objects(con)
    for name, kind in objs.items():
        t = TABLES.get(name)
        if t is None:
            continue
        con.execute(f"COMMENT ON {kind} {name} IS '{_q(t.description)} Grain: {t.grain}. Source: {_q(t.source)}'")
        actual = [r[0] for r in con.execute(
            "SELECT column_name FROM duckdb_columns() WHERE table_name = ?", [name]).fetchall()]
        for c in actual:
            d = col_desc(t, c)
            if d:
                con.execute(f"COMMENT ON COLUMN {name}.{c} IS '{_q(d)}'")


def undocumented(con: duckdb.DuckDBPyConnection) -> list[str]:
    """Objects or columns present in the database but missing from the dictionary (or vice versa)."""
    problems = []
    for name in _objects(con):
        t = TABLES.get(name)
        if t is None:
            problems.append(f"table {name}: not in dictionary")
            continue
        actual = [r[0] for r in con.execute(
            "SELECT column_name FROM duckdb_columns() WHERE table_name = ? ORDER BY column_index", [name]).fetchall()]
        for c in actual:
            if not col_desc(t, c):
                problems.append(f"{name}.{c}: no description")
        if list(t.columns) != actual:
            problems.append(f"{name}: dictionary columns {list(t.columns)} != actual {actual}")
    return problems


def _stats(con: duckdb.DuckDBPyConnection) -> dict[str, dict]:
    out = {}
    objs = _objects(con)
    for name, t in TABLES.items():
        if name not in objs:
            continue
        cols = set(t.columns)
        tcol = "ts_utc" if "ts_utc" in cols else ("day" if "day" in cols else None)
        if tcol:
            n, lo, hi = con.execute(f"SELECT count(*), min({tcol}), max({tcol}) FROM {name}").fetchone()
        else:
            n, lo, hi = con.execute(f"SELECT count(*) FROM {name}").fetchone()[0], None, None
        out[name] = {"rows": n, "first": str(lo)[:19] if lo else None, "last": str(hi)[:19] if hi else None}
    return out


def _coverage() -> list[tuple]:
    path = DATA / "coverage.parquet"
    if not path.exists():
        return []
    return duckdb.sql(f"""
        SELECT dataset, count(*), round(avg(coverage) * 100, 2), count(*) FILTER (WHERE coverage < 0.99)
        FROM '{path.as_posix()}' GROUP BY 1 ORDER BY 1""").fetchall()


def write_docs(con: duckdb.DuckDBPyConnection) -> tuple[str, str]:
    DOCS.mkdir(exist_ok=True)
    stats = _stats(con)
    cov = _coverage()
    flagged = con.execute("""SELECT CAST(ts_local AS DATE), strftime(ts_local, '%H:00'), count(*)
                             FROM lbmp_zone_hourly WHERE rt_flag IS NOT NULL GROUP BY ALL ORDER BY 1, 2""").fetchall() \
        if "lbmp_zone_hourly" in stats else []
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")

    md = [f"# NYISO data dictionary",
          "",
          f"_Generated by `nyiso docs` on {generated} from `src/nyiso/dictionary.py` plus live statistics. "
          "Do not edit by hand: change the dictionary and regenerate._",
          "",
          "The same descriptions are stored as DuckDB comments: "
          "`SELECT table_name, column_name, comment FROM duckdb_columns() WHERE NOT internal`.",
          "",
          "## Conventions", ""]
    for title, text in CONVENTIONS:
        md += [f"- **{title}.** {text}"]
    md += ["", "## Contents", "", "| Table | Layer | Grain | Rows | First (ts_utc or local day) | Last (ts_utc or local day) |", "|---|---|---|---:|---|---|"]
    for name, t in TABLES.items():
        s = stats.get(name, {})
        md.append(f"| [`{name}`](#{name}) | {t.layer} | {t.grain} | {s.get('rows', 0):,} | "
                  f"{s.get('first') or ''} | {s.get('last') or ''} |")
    if cov:
        md += ["", "## Coverage (`nyiso validate`)", "", "| Dataset | Days | Mean coverage % | Days < 99% |",
               "|---|---:|---:|---:|"]
        md += [f"| {d} | {n} | {c} | {b} |" for d, n, c, b in cov]
    if flagged:
        md += ["", "## Flagged hours (`lbmp_zone_hourly.rt_flag`)", "", "| Day | Hour (local) | Zones |", "|---|---|---:|"]
        md += [f"| {d} | {h} | {n} |" for d, h, n in flagged]
    for layer, title in [("curated", "Curated datasets (DuckDB views over Parquet)"),
                         ("derived", "Derived tables (built by `nyiso build`)"), ("reference", "Reference tables")]:
        md += ["", f"## {title}"]
        for name, t in TABLES.items():
            if t.layer != layer:
                continue
            md += ["", f"### {name}", "", t.description, "",
                   f"- **Grain:** {t.grain}", f"- **Key:** `{', '.join(t.key)}`", f"- **Source:** {t.source}"]
            md += [f"- **Note:** {n}" for n in t.notes]
            md += ["", "| Column | Description |", "|---|---|"]
            md += [f"| `{c}` | {col_desc(t, c)} |" for c in t.columns]
    md += ["", "## Files", "", "| Path | Contents |", "|---|---|"]
    md += [f"| `{p}` | {d} |" for p, d in FILES.items()]
    md_text = "\n".join(md) + "\n"
    (DOCS / "DATA.md").write_text(md_text, encoding="utf-8")

    payload = {
        "generated": generated,
        "conventions": [{"title": a, "text": b} for a, b in CONVENTIONS],
        "files": FILES,
        "tables": {name: {"layer": t.layer, "description": t.description, "grain": t.grain, "key": list(t.key),
                          "source": t.source, "notes": list(t.notes), **stats.get(name, {}),
                          "columns": {c: col_desc(t, c) for c in t.columns}}
                   for name, t in TABLES.items()},
    }
    (DOCS / "data_dictionary.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return str(DOCS / "DATA.md"), str(DOCS / "data_dictionary.json")
